name: Deploy to Cloudflare Workers

on:
  release:
    types: [published]
  schedule:
    - cron: "0 14 * * 5"
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: formiqstudio-project-jk-zk
          env-slug: prod
          secret-path: /journeylogs

      - run: bun install

      - name: Build
        run: NITRO_PRESET=cloudflare-module bun run build

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
